apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  AMQP_HOST: ""
  ANALYTICS_SERVICE_HOST: "analytics-service"
  ANALYTICS_SERVICE_PORT: "3090"
  APISERVER_PRIVILEGED_HOST: "apiserver"
  APISERVER_PRIVILEGED_PORT: "3091"
  AWS_S3_ACCESS_KEY_ID: ""
  AWS_S3_BUCKET: ""
  AWS_S3_SECRET_ACCESS_KEY: ""
  CDN: "/cdn"
  DISABLE_CI_CD_SERVICE: "true"
  CI_CD_USE_NODE_POOLS: ""
  CI_CD_USE_RESOURCE_CONSTRAINTS: ""
  CORE_DB_HOST: "dais-core-db"
  CORE_DB_PORT: "8000"
  CORE_DB_PORT_PRIVILEGED: "7007"
  CORE_DOCKER_REGISTRY: ""
  CORE_USES_IMAGE_PULL_SECRETS: ""
  SEQUELIZE_DB_DIALECT: "mssql"
  DB_HOST: "#{SQLSERVERNAME}#.database.windows.net"
  DB_PORT: "1433"
  DB_USER: "#{SQLSERVERUSER}#"
  DEFAULT_GATEWAY_ROUTE_TIMEOUT: "120"
  DISABLE_MODEL_UPLOADS: "true"
  DOCKERMODELRUNNER_MEMORY: "16000"
  DOMAIN_NAME: "#{DAISDOMAINNAME}#"
  FILE_MANAGER_HOST: "file-manager"
  FILE_MANAGER_PORT: "8000"
  FILE_SYSTEM_TYPE: "azure"
  FILESYSTEM_SERVICE_ACCOUNT: "" # needs to be addressed with Pod Identity
  GCP_BUCKET: ""
  GCP_QUARANTINED_BUCKET: ""
  GCP_SCANNED_BUCKET: ""
  GCP_UNSCANNED_BUCKET: ""
  GCP_CDN_BUCKET: ""
  GCP_KEY_FILE: ""
  GCP_EXPORT_BUCKET: ""
  KUBERNETES_NAMESPACE: "#{KUBERNETESNAMESPACE}#"
  LOGSTASH_HOST: ""
  MALWARE_SCAN: "false"
  MINIO_ACCESS_KEY: ""
  PROJECT_DB_HOST: "dais-project-db"
  PROJECT_DB_PORT: "8000"
  PROJECT_DB_PORT_PRIVILEGED: "7007"
  QUEUE_LOGGING: "logging"
  QUEUE_MAIL: "mail"
  QUEUE_MODEL_ERRORS: "modelerrors"
  QUEUE_PROCESS_ERRORS: "processerrors"
  QUEUE_RESULTS: "results"
  QUEUE_RUNS_STATUS: "runs.status"
  QUEUE_SLACK: "slack"
  QUEUE_SUBMISSION_FINISH: "submissionfinished"
  QUEUE_TASKS: "tasks"
  RABBITMQ_DEFAULT_USER: ""
  REDIS_HOST: "#{REDISCACHEHOSTNAME}#.redis.cache.windows.net"
  REDIS_PORT: "6380"
  REDIS_USE_TLS: "true"
  SLACK_CHANNEL: ""
  SLACK_USERNAME: ""
  SUPPORT_MAIL: "1@2.com" # TODO?
  TWILIO_FROM_PHONE: ""
  USE_LOGSTASH: "false"
  USE_S3: "false"
  PROJECT_SERVICES_JENKINS_USER: ""
  ARBITRARY_CODE_DAIS_ADMINS_ONLY: "true"
  DISABLE_LEGACY_FRONTEND_WRAPPER: "false"
  SUPER_ADMIN_HOST: "dais"
  SUPER_ADMIN_HOST_LEGACY_SUPPORT: "false"
  GCP_PROJECT: ""
  USE_APM: "false"
  PROJECT_SERVICES_JENKINS_DOCKER_REGISTRY: ""
  PROJECT_SERVICES_JENKINS_DOCKER_REGISTRY_USERNAME: ""
  PROJECT_SERVICES_JENKINS_DOCKER_REGISTRY_PASSWORD: ""
  PROJECT_SERVICES_JENKINS_DOCKER_REGISTRY_AUTH_TYPE: ""
  PROJECT_SERVICES_USE_IMAGE_PULL_SECRETS: ""
  HOSTS_TO_ALLOW_PROJECT_CREATION: "creator"
  HOSTS_TO_ALLOW_JS_BUNDLE_OVERWRITE: "creator"
  HOSTS_TO_ALLOW_USERGROUP_MODIFICATION: "creator"
  HOSTS_TO_ALLOW_CI_CD_SERVICE: "creator"
  HOSTS_TO_ALLOW_USER_INVITE: "creator"
  MIN_JAVAMODELRUNNER_PROCESSES: "2"
  MAX_JAVAMODELRUNNER_PROCESSES: "60"
  MIN_RMODELRUNNER_PROCESSES: "1"
  MAX_RMODELRUNNER_PROCESSES: "30"
  MIN_DOCKERMODELRUNNER_PROCESSES: "2"
  MAX_DOCKERMODELRUNNER_PROCESSES: "30"
  DAIS_RELEASE_VERSION: "0.0.0"
  # Need to rename for consistency:
  AZURE_PROJECTS_CONTAINER_NAME: "poaz01stg007-blb-dais" # TODO - igmdata?
  USE_EXTERNAL_K8S_CLUSTER: "false"
  EXTERNAL_K8S_CLUSTER_PROVIDER: "azure"
  EXTERNAL_GCP_CLUSTER_PROJECT: ""
  EXTERNAL_GCP_CLUSTER_NAME: ""
  EXTERNAL_GCP_CLUSTER_ZONE: ""
  EXTERNAL_CLUSTER_REVERSE_PROJECT_GATEWAY_LOAD_BALANCER_IP: ""
  APP_LINEAGE_MODE: "STANDARD"
  MESSAGE_QUEUE_PROVIDER: "azure"
  AZURE_MESSAGE_BUS_HOST: "#{SERVICEBUSNAME}#.servicebus.windows.net"
  AZURE_MESSAGE_BUS_USER: "dais"
  AZURE_STORAGE_ACCOUNT_NAME: "#{STORAGEACCOUNTNAME}"
  DOCKERMODELRUNNER_IMAGE_TAG: "#{ACRNAME}#.azurecr.io/dcceew/apps/dais/get-results-dockermodelrunner:2.1.0-diser.136-07bf1944ef73a328cd93e7a2c9a57251298785c5"
  ANALYTICS_DB_NAME: "dais"
  AUTHSERVICE_DB_NAME: "dais"
  DAIS_CORE_DB_NAME: "dais"
  GATEWAY_DB_NAME: "dais"
  GETRESULTS_DB_NAME: "dais"
  MODULAR_FRONTEND_STORE_DB_NAME: "dais"
  PROJECTS_DB_NAME: "dais"
  WEBSITE_DB_NAME: "dais"
  # TODO: need app insights deployed and key saved to kv
  AZURE_APP_INSIGHTS_CONNECTION_STRING: "#{AppInsightsConnectionString}"
  AZURE_AD_REGISTERED_GROUP_ID: "dd723e7e-e07f-4fbe-b7ac-73cebffc5791" # TODO azdo #430048
  AZURE_AD_PRIVILEGED_GROUP_ID: "b970e64f-f250-41bc-9b99-515fa3bf9940" # TODO azdo #430048
  AZURE_AD_ADMIN_GROUP_ID: "ce9d7048-ccbc-48e2-a98a-8ad090dba5a6" # TODO azdo #430048
  CLEAN_UP_DOCKERMODELRUNNER_PODS: "true"
  USE_AAD_DB_AUTH: "true"
  SSO_CONFIGURATION_PATH: "/sso-config/sso-config.yml"
  REVERSE_PROJECT_GATEWAY_SECRET: "x"
  MODEL_NODE_SELECTOR_KEY: "node-pool-category"
  MODEL_NODE_SELECTOR_VALUE: "application"
