---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-crb
subjects:
  - kind: ServiceAccount
    name: dockermodelrunner-cluster-service-account
    namespace: {{ $kubernetesNamespace }}
roleRef:
  kind: ClusterRole
  name: dockermodelrunner-cluster-service-account
  apiGroup: rbac.authorization.k8s.io
