---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: auth-service
        aadpodidbinding: poaz01dais001
    spec:
      imagePullSecrets:
        - name: core-docker-registry-secret
      securityContext:
        fsGroup: 9000
      containers:
        - name: auth-service
          imagePullPolicy: Always
          image: #{ACRNAME}#.azurecr.io/dcceew/apps/dais/auth-service:2.1.0-diser.136-07bf1944ef73a328cd93e7a2c9a57251298785c5
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: daiscore-secret
            - configMapRef:
                name: env-config
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 1000Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          volumeMounts:
            - mountPath: /sso-config
              name: sso-configuration-yaml
          securityContext:
            runAsUser: 9000
            allowPrivilegeEscalation: false
      nodeSelector:
        "beta.kubernetes.io/os": linux
        "node-pool-category": application
      volumes:
        - name: sso-configuration-yaml
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "sso-configuration-yaml"
