---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: analytics-service
        allowProjectResourceAccess: "allow"
        aadpodidbinding: poaz01dais001
    spec:
      imagePullSecrets:
        - name: core-docker-registry-secret
      securityContext:
        fsGroup: 9000
      containers:
        - name: analytics-service
          imagePullPolicy: Always
          image: {{ $acrName }}.azurecr.io/dcceew/apps/dais/analytics-service:2.1.0-diser.136-07bf1944ef73a328cd93e7a2c9a57251298785c5
          ports:
            - containerPort: 3090
          envFrom:
            - secretRef:
                name: daiscore-secret
            - configMapRef:
                name: env-config
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 1000Mi
              cpu: 500m
          volumeMounts:
            - name: daiscore-secret
              mountPath: /mnt/daiscore-secret
              readOnly: true
          securityContext:
            runAsUser: 9000
            allowPrivilegeEscalation: false
      nodeSelector:
        "beta.kubernetes.io/os": linux
        "node-pool-category": application
      volumes:
        - name: daiscore-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "daiscore-secret"
