---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-namespace-comms
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels: {}
  egress:
    - to:
        - podSelector:
            matchLabels: {}
