---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-blob-storage
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
