---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-servicebus
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 5671
