---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-nmi
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 127.0.0.1/32
      ports:
        - protocol: TCP
          port: 2579
