---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Ingress
    - Egress
