---
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: daiscore-secret
# stringData:
#   API_SECRET: ""
#   DB_PASSWORD: ""
#   PROJECT_RESOURCES_API_SECRET: ""
#   REDIS_PASS: ""
#   AZURE_MESSAGE_BUS_PASS: ""
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: daiscore-secret
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: daiscore-secret
      type: Opaque # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
      data:
        - objectName: API-SECRET # name of the mounted content to sync. this could be the object name or the object alias
          key: API_SECRET # name of the Kubernetes Secret object
        - objectName: DB-PASSWORD # name of the mounted content to sync. this could be the object name or the object alias
          key: DB_PASSWORD # name of the Kubernetes Secret object
        - objectName: REDIS-PASS # name of the mounted content to sync. this could be the object name or the object alias
          key: REDIS_PASS # name of the Kubernetes Secret object
        - objectName: AZURE-MESSAGE-BUS-PASS
          key: AZURE_MESSAGE_BUS_PASS
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "poaz01key010"
    cloudName: ""
    objects: "array:\n  - |\n    objectName: API-SECRET\n    objectType: secret\n    objectVersion: \"\"\n  - |\n    objectName: DB-PASSWORD\n    objectType: secret\n    objectVersion: \"\"      \n  - |\n    objectName: REDIS-PASS\n    objectType: secret\n    objectVersion: \"\" \n  - |\n    objectName: AZURE-MESSAGE-BUS-PASS\n    objectType: secret\n    objectVersion: \"\"\n"
    tenantId: "8f73f427-32e5-4a3b-8d42-b369b956a96b"
