---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  ports:
    - name: main
      port: 3090
      protocol: TCP
      targetPort: 3090
  selector:
    app: analytics-service
  type: ClusterIP
