---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: #{KUBERNETESNAMESPACE}#
spec:
  ports:
    - name: main
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: website
  type: ClusterIP
