---
apiVersion: v1
kind: Service
metadata:
  name: results-service
spec:
  ports:
    - name: main
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: results-service
  type: ClusterIP
