---
apiVersion: v1
kind: Service
metadata:
  name: taskgen-j3u453cewp5q
spec:
  ports:
    - name: taskgen-j3u453cewp5q
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: taskgen-j3u453cewp5q
  type: ClusterIP
