---
apiVersion: v1
kind: Service
metadata:
  name: dais-project-db
spec:
  ports:
    - name: main
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: privileged
      port: 7007
      protocol: TCP
      targetPort: 7007
  selector:
    app: dais-project-db
  type: ClusterIP
  sessionAffinity: ClientIP
