---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  ports:
    - name: main
      port: 3090
      protocol: TCP
      targetPort: 3090
    - name: privileged
      port: 3091
      protocol: TCP
      targetPort: 3091
  selector:
    app: get-results-apiserver
  type: ClusterIP
